=== asombrosio/SW2Recetario/Practica1SWII/files/dtd/recetario.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/recetarioDTD.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Recetario SYSTEM "recetarioDTD.dtd">

    <Recetario>
    ...
    </Recetario>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Recetario (nombre|recetas|precio)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT recetas (recetas|nombre|ingrediente|precio)*>
<!ATTLIST recetas
    dificultad CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ingrediente (#PCDATA|ingrediente)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT precio (#PCDATA)>

=== asombrosio/SW2Recetario/Practica1SWII/files/xml/recetarioDTD.xml
<?xml version="1.0"?>
<!DOCTYPE Recetario SYSTEM "../dtd/recetario.dtd">
<Recetario>
    <nombre>Recetario1</nombre>
    <recetas>
        <recetas dificultad="Dificil">
            <nombre>Lasanna</nombre>
            <ingrediente>
                <ingrediente>Tomate</ingrediente>
                <ingrediente>Carne</ingrediente>
                <ingrediente>Pasta</ingrediente>
                <ingrediente>Queso</ingrediente>
                <ingrediente>Aceite</ingrediente>
                <ingrediente>Sal</ingrediente>
                <ingrediente>Bechamel</ingrediente>
            </ingrediente>
            <precio>12.0</precio>
        </recetas>
        <recetas dificultad="Facil">
            <nombre>Sandwich de pavo</nombre>
            <ingrediente>
                <ingrediente>Pavo</ingrediente>
                <ingrediente>Pan</ingrediente>
            </ingrediente>
            <precio>1.5</precio>
        </recetas>
        <recetas dificultad="Facil">
            <nombre>Filete de ternera</nombre>
            <ingrediente>
                <ingrediente>Carne de ternera</ingrediente>
                <ingrediente>Aceite</ingrediente>
                <ingrediente>Sal</ingrediente>
            </ingrediente>
            <precio>1.0</precio>
        </recetas>
    </recetas>
    <precio>20.0</precio>
</Recetario>
